services:
  mariadb:
    container_name: mariadb-11.0.2-jammy
    image: 'mariadb:11.0.2-jammy'
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: verysecret
    ports:
      - 3308:3306
  adminer:
    container_name: adminer-4.8.0-standalone
    image: adminer:4.8.0-standalone
    restart: always
    ports:
      - 9080:8080

  smtp4dev:
    image: rnwood/smtp4dev:v3
    restart: always
    ports:
      - 9081:80
      - 9025:25
